import { normalizeBlindLevels } from './defaultBlinds.js';
import { POSITION_MAP } from './pokerConstants.js';
import { applyPositionsForRound, createHandStateWithBlinds, getCurrentLevel } from './pokerLogic.js';
export function createPlayer({ name, index, playerCount, startStack }) { const id=globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():`p_${Date.now()}_${index}`; return { id, seatIndex:index, name:name?.trim()||`Spiller ${index+1}`, chips:startStack, active:true, eliminated:false, currentPosition:POSITION_MAP[playerCount]?.[index]||'Spiller' }; }
export function startTournamentFromSetup({ currentState, playerNames, blindLevels, startStack }) { const parsed=Number(startStack)||2500; const count=playerNames.length; let n={...currentState, players:playerNames.map((name,index)=>createPlayer({name,index,playerCount:count,startStack:parsed})), blinds:normalizeBlindLevels(blindLevels), startStack:parsed, currentLevelIndex:0, currentPot:0, roundNumber:1, dealerIndex:count-1, timerRunning:false, levelEndsAt:null, handState:null}; const first=getCurrentLevel(n); n.timeRemainingSec=first.duration*60; n=applyPositionsForRound(n); n=createHandStateWithBlinds(n); return n; }
export function toggleTimer(state) { if(state.timerRunning){ const timeRemainingSec=state.levelEndsAt?Math.max(0,Math.ceil((state.levelEndsAt-Date.now())/1000)):state.timeRemainingSec; return {...state,timerRunning:false,levelEndsAt:null,timeRemainingSec}; } return {...state,timerRunning:true,levelEndsAt:Date.now()+state.timeRemainingSec*1000}; }
export function changeLevel(state, delta) { const nextIndex=Math.max(0,Math.min(state.blinds.length-1,state.currentLevelIndex+delta)); if(nextIndex===state.currentLevelIndex)return state; const n={...state,currentLevelIndex:nextIndex}; const cur=getCurrentLevel(n); n.timeRemainingSec=cur.duration*60; n.levelEndsAt=n.timerRunning?Date.now()+n.timeRemainingSec*1000:null; return n; }
export function updateTimerFromClock(state, now=Date.now()) { if(!state.timerRunning)return{state,levelChanged:false}; let n={...state}; if(!n.levelEndsAt)n.levelEndsAt=now+n.timeRemainingSec*1000; let levelChanged=false; while(n.levelEndsAt<=now&&n.currentLevelIndex<n.blinds.length-1){ n.currentLevelIndex+=1; n.levelEndsAt+=getCurrentLevel(n).duration*60*1000; levelChanged=true; } n.timeRemainingSec=Math.max(0,Math.ceil((n.levelEndsAt-now)/1000)); if(n.timeRemainingSec<=0&&n.currentLevelIndex>=n.blinds.length-1){ n.timeRemainingSec=0; n.levelEndsAt=null; n.timerRunning=false; } return {state:n,levelChanged}; }
export function saveEditedStacks(state, stackValues) { let n={...state,players:state.players.map((p,i)=>{const chips=Math.max(0,Number(stackValues[i])||0); return {...p,chips,eliminated:chips<=0,active:chips>0};})}; return applyPositionsForRound(n); }
